Add specs to test Array#select form of ScopeProxy#select
These tests should fail. The fix is in the next commit.

This should raise:

    ArgumentError: Call this with at least one field

This is because the block is not being passed through.